#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Generate the POD6 documentation for the various classes
#

export DOC=$THIS_DIR/doc

if [ ! -d $DOC ]
then
    mkdir $DOC
fi


raku -Ilib --doc=HTML lib/Date/Calendar/Armenian.rakumod       > $DOC/Armenian.html
raku -Ilib --doc=HTML lib/Date/Calendar/Armenian/Names.rakumod > $DOC/Names.html
raku -Ilib --doc=HTML util/gener-test-0.1.0.raku               > $DOC/gener-test.html
perldoc -o html -d $DOC/mk-test-conv.html util/mk-test-conv.pl

case $1 in
   --show)
     cd $DOC
     firefox Armenian.html Names.html gener-test.html mk-test-conv.html
     ;;
esac
